Add environment.yml to fix dependencies when running tests.
When attempting to run tests, I had the following issue:

        (mgc) pnguyen@0584:/Users/pnguyen/code/metagraph-cuda$ pytest
        ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
        pytest: error: unrecognized arguments: --cov-report --cov=metagraph_cuda metagraph_cuda/tests
          inifile: /Users/pnguyen/code/metagraph-cuda/setup.cfg
          rootdir: /Users/pnguyen/code/metagraph-cuda

        (mgc) pnguyen@0584:/Users/pnguyen/code/metagraph-cuda$

This was partially due to a dependence on setuptools.

This commit adds an environment.yml that is intended to make it easier to run tests without having to worry about dependencies if we run the tests via something like the following:
        conda env create
        conda activate mgc
        # we need to handle metagraph installation here ; this commit doesn't handle dependencies on metagraph.
        pre-commit install
        python setup.py develop
        pytest